using System.Collections.Generic;

namespace GoogleApi.Entities.PlacesNew.Search.Common;

/// <summary>
/// Routing Summary.
/// </summary>
public class RoutingSummary
{
    /// <summary>
    /// The legs of the trip.
    /// When you calculate travel duration and distance from a set origin, legs contains a single leg containing the duration and distance from
    /// the origin to the destination.When you do a search along route, legs contains two legs: one from the origin to place,
    /// and one from the place to the destination.
    /// </summary>
    public virtual IEnumerable<Leg> Legs { get; set; }

    /// <summary>
    /// A link to show directions on Google Maps using the waypoints from the given routing summary.
    /// The route generated by this link is not guaranteed to be the same as the route used to generate the routing summary.
    /// The link uses information provided in the request, from fields including routingParameters and searchAlongRouteParameters when applicable,
    /// to generate the directions link.
    /// </summary>
    public virtual string DirectionsUri { get; set; }
}