namespace GoogleApi.Entities.Translate.Common.Enums.Extensions;

/// <summary>
/// String Extensions.
/// </summary>
public static class StringExtension
{
    /// <summary>
    /// Gets the <see cref="Language"/> for the specified ISO-639-1/(2) code.
    /// </summary>
    /// <param name="code">The ISO-639-1 code.</param>
    /// <returns>the <see cref="Language"/> matching the passed <paramref name="code"/>.</returns>
    public static Language? FromCode(this string code)
    {
        return code switch
        {
            "af" => Language.Afrikaans,
            "sq" => Language.Albanian,
            "am" => Language.Amharic,
            "ar" => Language.Arabic,
            "hy" => Language.Armenian,
            "az" => Language.Azeerbaijani,
            "eu" => Language.Basque,
            "be" => Language.Belarusian,
            "bn" => Language.Bengali,
            "bs" => Language.Bosnian,
            "bg" => Language.Bulgarian,
            "ca" => Language.Catalan,
            "ceb" => Language.Cebuano,
            "ny" => Language.Chichewa,
            "zh" => Language.Chinese_Simplified,
            "zh-CN" => Language.Chinese_Simplified,
            "zh-TW" => Language.Chinese_Traditional,
            "co" => Language.Corsican,
            "hr" => Language.Croatian,
            "cs" => Language.Czech,
            "da" => Language.Danish,
            "nl" => Language.Dutch,
            "en" => Language.English,
            "eo" => Language.Esperanto,
            "et" => Language.Estonian,
            "tl" => Language.Filipino,
            "fi" => Language.Finnish,
            "fr" => Language.French,
            "fy" => Language.Frisian,
            "gl" => Language.Galician,
            "ka" => Language.Georgian,
            "de" => Language.German,
            "el" => Language.Greek,
            "gu" => Language.Gujarati,
            "ht" => Language.Haitian_Creole,
            "ha" => Language.Hausa,
            "haw" => Language.Hawaiian,
            "iw" => Language.Hebrew,
            "hi" => Language.Hindi,
            "hmn" => Language.Hmong,
            "hu" => Language.Hungarian,
            "is" => Language.Icelandic,
            "ig" => Language.Igbo,
            "id" => Language.Indonesian,
            "ga" => Language.Irish,
            "it" => Language.Italian,
            "ja" => Language.Japanese,
            "jw" => Language.Javanese,
            "kn" => Language.Kannada,
            "kk" => Language.Kazakh,
            "km" => Language.Khmer,
            "ko" => Language.Korean,
            "ku" => Language.Kurdish,
            "ky" => Language.Kyrgyz,
            "lo" => Language.Lao,
            "la" => Language.Latin,
            "lv" => Language.Latvian,
            "lt" => Language.Lithuanian,
            "lb" => Language.Luxembourgish,
            "mk" => Language.Macedonian,
            "mg" => Language.Malagasy,
            "ms" => Language.Malay,
            "ml" => Language.Malayalam,
            "mt" => Language.Maltese,
            "mi" => Language.Maori,
            "mr" => Language.Marathi,
            "mn" => Language.Mongolian,
            "my" => Language.Burmese,
            "ne" => Language.Nepali,
            "no" => Language.Norwegian,
            "ps" => Language.Pashto,
            "fa" => Language.Persian,
            "pl" => Language.Polish,
            "pt" => Language.Portuguese,
            "ma" => Language.Punjabi,
            "ro" => Language.Romanian,
            "ru" => Language.Russian,
            "sm" => Language.Samoan,
            "gd" => Language.Scots_Gaelic,
            "sr" => Language.Serbian,
            "st" => Language.Sesotho,
            "sn" => Language.Shona,
            "sd" => Language.Sindhi,
            "si" => Language.Sinhala,
            "sk" => Language.Slovak,
            "sl" => Language.Slovenian,
            "so" => Language.Somali,
            "es" => Language.Spanish,
            "su" => Language.Sundanese,
            "sw" => Language.Swahili,
            "sv" => Language.Swedish,
            "tg" => Language.Tajik,
            "ta" => Language.Tamil,
            "te" => Language.Telugu,
            "th" => Language.Thai,
            "tr" => Language.Turkish,
            "uk" => Language.Ukrainian,
            "ur" => Language.Urdu,
            "uz" => Language.Uzbek,
            "vi" => Language.Vietnamese,
            "cy" => Language.Welsh,
            "xh" => Language.Xhosa,
            "yi" => Language.Yiddish,
            "yo" => Language.Yoruba,
            "zu" => Language.Zulu,
            _ => Language.English
        };
    }
}