using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using GoogleApi.Entities.Common.Enums;
using GoogleApi.Entities.Maps.Common;
using GoogleApi.Entities.Places.Common;
using GoogleApi.Helpers;

namespace GoogleApi.Entities.Places.PlacesAutoComplete.Request
{
	/// <summary>
	/// The Google Places API is a service that returns information about a "place" (hereafter referred to as a Place) — defined within this API as an establishment, a geographic location, or prominent point of interest — using an HTTP request. Place requests specify locations as latitude/longitude coordinates.
	/// Two basic Place requests are available: a Place Search request and a Place Details request. Generally, a Place Search request is used to return candidate matches, while a Place Details request returns more specific information about a Place.
	/// This service is designed for processing place requests generated by a user for placement of application content on a map; this service is not designed to respond to batch of offline queries, which are a violation of its terms of use.
	/// </summary>
    public class PlacesAutoCompleteRequest : PlacesBaseRequest
	{
		protected internal override string BaseUrl
		{
			get
			{
                return base.BaseUrl + "autocomplete/";
			}
		}

		/// <summary>
		/// Your application's API key. This key identifies your application for purposes of quota management and so that Places 
		/// added from your application are made immediately available to your app. Visit the APIs Console to create an API Project and obtain your key.
		/// </summary>
        public virtual string ApiKey { get; set; } 

        /// <summary>
        /// The text string on which to search. The Place service will return candidate matches based on this string and order results based on their perceived relevance.
        /// </summary>
        public virtual string Input { get; set; } 

        /// <summary>
        /// The character position in the input term at which the service uses text for predictions. For example, if the input is 'Googl' and the completion point is 3, the service will match on 'Goo'. The offset should generally be set to the position of the text caret. If no offset is supplied, the service will use the entire term.        
        /// </summary>
        public virtual string Offset { get; set; }

        /// <summary>
        /// The point around which you wish to retrieve Place information. Must be specified as latitude,longitude.
		/// </summary>
        public virtual Location Location { get; set; }

        /// <summary>
        /// The distance (in meters) within which to return Place results. Note that setting a radius biases results to the indicated area, but may not fully restrict results to the specified area. See Location Biasing below.
		/// </summary>
        public virtual double? Radius { get; set; }

		/// <summary>
        /// The language in which to return results. See the supported list of domain languages. Note that we often update supported languages so this list may not be exhaustive. If language is not supplied, the Place service will attempt to use the native language of the domain from which the request is sent.
		/// </summary>
        public virtual string Language { get; set; }

		/// <summary>
        /// The types of Place results to return. See Place Types below. If no type is specified, all types will be returned.
        /// See the list of supported types - https://developers.google.com/maps/documentation/places/supported_types
		/// </summary>
        public virtual string Types { get; set; }

        /// <summary>
        /// The component filters, separated by a pipe (|). Each component filter consists of a component:value pair and will fully restrict the results from the geocoder. For more information see Component Filtering.
		/// </summary>
        public virtual Dictionary<Component, string> Components { get; set; }
        
        public override bool IsSsl
		{
			get
			{
				return true;
			}
			set
			{
				throw new NotSupportedException("This operation is not supported, PlacesRequest must use SSL");
			}
		}

        protected override IDictionary<string, string> GetQueryStringParameters()
		{
            if (string.IsNullOrEmpty(ApiKey))
                throw new ArgumentException("ApiKey must not null or empty");

            if (string.IsNullOrEmpty(Input))
                throw new ArgumentException("_input must not null or empty");

            if (Radius.HasValue && (Radius > 50000 || Radius < 1))
				throw new ArgumentException("Radius must be greater than or equal to 1 and less than or equal to 50000.");

			var parameters = base.GetQueryStringParameters();

            parameters.Add("key", ApiKey);
            parameters.Add("input", Input);

            if (!string.IsNullOrEmpty(Offset))
                parameters.Add("offset", Offset);

            if (Location != null)
                parameters.Add("location", Location.ToString());
	
            if (Radius.HasValue)
				parameters.Add("radius", Radius.Value.ToString(CultureInfo.InvariantCulture));

            if (!string.IsNullOrEmpty(Language))
                parameters.Add("language", Language);

            if (!string.IsNullOrEmpty(Types))
                parameters.Add("types", Types);

            if (Components != null && Components.Any())
                parameters.Add("components", string.Join("|", Components.Select(x => string.Format("{0}:{1}", x.Key, x.Value))));
            
            return parameters;
		}
	}
}
